# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loan_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication
from typing import Callable
class Ui_LoanBook(object):
    def setupUi(self, MainWindow: QMainWindow):
        MainWindow.setFixedSize(800, 600)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(200, 300, 231, 72))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")



        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(260, 130, 351, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_isbn = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_isbn.setObjectName("line_isbn")
        self.verticalLayout.addWidget(self.line_isbn)
        self.line_member_id = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_member_id.setObjectName("line_member_id")
        self.verticalLayout.addWidget(self.line_member_id)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(170, 140, 81, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_isbn = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_isbn.setObjectName("label_isbn")
        self.verticalLayout_2.addWidget(self.label_isbn)
        self.label_member_iid = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_member_iid.setObjectName("label_member_iid")
        self.verticalLayout_2.addWidget(self.label_member_iid)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(440, 300, 171, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_loan_book = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_loan_book.setObjectName("btn_loan_book")
        self.horizontalLayout.addWidget(self.btn_loan_book)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 490, 101, 61))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")





        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow: QMainWindow):
        _translate: Callable[[str, str], str] = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Loan Book"))
        self.label_isbn.setText(_translate("MainWindow", "             ISBN"))
        self.label_member_iid.setText(_translate("MainWindow", " Member ID"))
        self.btn_loan_book.setText(_translate("MainWindow", "Loan Book"))




if __name__ == "__main__":
    import sys
    app: QApplication = QtWidgets.QApplication(sys.argv)
    MainWindow: QMainWindow = QtWidgets.QMainWindow()
    ui: Ui_LoanBook = Ui_LoanBook()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
