# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Callable

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow: QMainWindow) -> None:
        MainWindow.setFixedSize(800, 600)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 781, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_add_book = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_add_book.setObjectName("btn_add_book")
        self.verticalLayout.addWidget(self.btn_add_book)
        self.btn_remove_book = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_remove_book.setObjectName("btn_remove_book")
        self.verticalLayout.addWidget(self.btn_remove_book)
        self.btn_add_member = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_add_member.setObjectName("btn_add_member")
        self.verticalLayout.addWidget(self.btn_add_member)
        self.btn_remove_member = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_remove_member.setObjectName("btn_remove_member")
        self.verticalLayout.addWidget(self.btn_remove_member)
        self.btn_show_books = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_show_books.setObjectName("btn_show_books")
        self.verticalLayout.addWidget(self.btn_show_books)
        self.btn_show_members = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_show_members.setObjectName("btn_show_members")
        self.verticalLayout.addWidget(self.btn_show_members)
        self.btn_loan_book = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_loan_book.setObjectName("btn_loan_book")
        self.verticalLayout.addWidget(self.btn_loan_book)
        self.btn_return_book = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_return_book.setObjectName("btn_return_book")
        self.verticalLayout.addWidget(self.btn_return_book)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow: QMainWindow) -> None:
        _translate: Callable[[str, str], str] = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_add_book.setText(_translate("MainWindow", "Add Book"))
        self.btn_remove_book.setText(_translate("MainWindow", "Remove Book"))
        self.btn_add_member.setText(_translate("MainWindow", "Add Member"))
        self.btn_remove_member.setText(_translate("MainWindow", "Remove Member"))
        self.btn_show_books.setText(_translate("MainWindow", "Show Books"))
        self.btn_show_members.setText(_translate("MainWindow", "Show Members"))
        self.btn_loan_book.setText(_translate("MainWindow", "Loan Book"))
        self.btn_return_book.setText(_translate("MainWindow", "Return Book"))


if __name__ == "__main__":
    import sys

    app: QApplication = QtWidgets.QApplication(sys.argv)
    MainWindow: QMainWindow = QtWidgets.QMainWindow()
    ui: Ui_MainWindow = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
